[package]
name = "tally_xml_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
roxmltree = "0.20"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.139"